### ISSUE TITLE
Better behavior/documentation around process exit

### ISSUE THREAD

**Issue by cespare** [cespare/flagconf#3]
Right now flagconf returns an error for any TOML errors, but calls `flag.Parse` so it ends up exiting on any flag errors. Also, TOML errors end up masking `-h` (see #1).

I like the convenience of `flag.Parse`; so maybe there should be two functions; one which prints useful info and exits (including if the error is with the TOML file); this function shouldn't return an error. Then a second function could return the appropriate flag/TOML error for the user to handle.

/cc @dominikh and @alytvynov for reckons

**Comment by awly** [comment]
How about `MustParse` with `ExitOnError` and `Parse` with `ContinueOnError`?

`MustParse` would be identical to current `Parse` with no error return and some helpful message + exit on TOML errors.

`Parse` would need error handling changed to `ContinueOnError`. It would also need Usage field set in FlagSet to prevent printing to stderr and a custom return type that contains usage info from package flag.

**Comment by cespare** [comment]
This sounds pretty good to me. I started to work on it.

> It would also need Usage field set in FlagSet to prevent printing to stderr and a custom return type that contains usage info from package flag.

Good call on this. It's a bit of a tricky rough edge. The return type could be `(msg string, err error)`, or could just be `error` but it's always of type `*FlagconfError`:

```
type FlagconfError struct {
  # Exactly one of FlagErr, TOMLErr is nil. If FlagErr is non-nil,
  # Usage contains the usage string printed by the flag package.
  TOMLErr error
  FlagErr error
  Usage   string
}
```

That's starting to get pretty cumbersome though.

To maintain similarity with the flag package, we could have something like

```
var Usage = func(err *FlagconfError) {
  if err.TOMLErr != nil {
    fmt.Fprintf(os.Stderr, "Cannot parse TOML config: %s\n", err.TOMLErr)
  }
  fmt.Fprint(os.Stderr, err.Usage)
}
```

which the user can override.

**Comment by awly** [comment]
I already have most of this done in a fork. Stand by for a pr.

**Comment by cespare** [comment]
OK thanks :)
