### ISSUE TITLE
Port to https://github.com/naoina/toml

### ISSUE THREAD

**Issue by flowchartsman** [cespare/flagconf#5]
BurntSushi/toml does not support the latest version of the spec, IIRC

**Comment by cespare** [comment]
Reference please? @BurntSushi is a TOML spec maintainer, so that would be somewhat surprising :)

**Comment by BurntSushi** [comment]
No, I am actually a bit behind. Been a crazy few months. I don't think I'm missing much though.

**Comment by cespare** [comment]
@BurntSushi thanks for the info.

@alaska let me know what functionality you're specifically missing.

**Comment by flowchartsman** [comment]
Raw strings spring to mind, unless those are supported now and I missed it. Which would be embarrassing. :)

**Comment by cespare** [comment]
They're supported, in both the single-line and multiline varieties:

http://play.golang.org/p/k98bMXjKnw

Found that useful for writing a regex in a configuration just recently.

**Comment by cespare** [comment]
@alaska I'm closing for now; let me know if there are any TOML features that would be useful in a flagconf file that you can't get from BurntSushi/toml and we can revisit. (Although I'd probably be inclined to just write a PR to get the feature into BurntSushi/toml.)

**Comment by flowchartsman** [comment]
Excellent! Will do.
