### ISSUE TITLE
Enhancement: Environment variable support.

### ISSUE THREAD

**Issue by flowchartsman** [cespare/flagconf#6]
Have you considered allowing environment variables to override the config file? It would be nice to have a library that did all three if for no other reason than avoiding leaking information in a process list, but still conforming to 12-factor style design and deployment.

As to precedence, I'm not sure whether command-line flags should take precedence over environment variables (I'm inclined to think flags > env > config), or whether a warning or error should be thrown if both are specified.

If this would be a welcome addition, I'd be happy to fork and issue a PR.

**Comment by cespare** [comment]
I'm of the opinion that environment variables are a poor configuration method for security reasons (leaking secrets to child processes and so forth) so I specifically don't want to support them.

There are other libraries similar to flagconf that support a wider array of configuration options includuing env vars; for instance, you might look at [github.com/koding/multiconfig](https://github.com/koding/multiconfig).

**Comment by flowchartsman** [comment]
Fair enough. Thanks for the rationale.
